/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as EnRouteImport } from './routes/en'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as EnProductsRouteImport } from './routes/en.products'
import { Route as EnInquiryRouteImport } from './routes/en.inquiry'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnApplicationsRouteImport } from './routes/en.applications'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as BrandsBrandRouteImport } from './routes/brands.$brand'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EnBrandsIndexRouteImport } from './routes/en.brands.index'
import { Route as EnProductsSlugRouteImport } from './routes/en.products.$slug'
import { Route as EnBrandsBrandRouteImport } from './routes/en.brands.$brand'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const EnProductsRoute = EnProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => EnRoute,
} as any)
const EnInquiryRoute = EnInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnApplicationsRoute = EnApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const BrandsBrandRoute = BrandsBrandRouteImport.update({
  id: '/brands/$brand',
  path: '/brands/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnBrandsIndexRoute = EnBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => EnRoute,
} as any)
const EnProductsSlugRoute = EnProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnProductsRoute,
} as any)
const EnBrandsBrandRoute = EnBrandsBrandRouteImport.update({
  id: '/brands/$brand',
  path: '/brands/$brand',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRouteWithChildren
  '/inquiry': typeof InquiryRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/en/about': typeof EnAboutRoute
  '/en/applications': typeof EnApplicationsRoute
  '/en/contact': typeof EnContactRoute
  '/en/inquiry': typeof EnInquiryRoute
  '/en/products': typeof EnProductsRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/brands/': typeof BrandsIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/brands/$brand': typeof EnBrandsBrandRoute
  '/en/products/$slug': typeof EnProductsSlugRoute
  '/en/brands/': typeof EnBrandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/inquiry': typeof InquiryRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/en/about': typeof EnAboutRoute
  '/en/applications': typeof EnApplicationsRoute
  '/en/contact': typeof EnContactRoute
  '/en/inquiry': typeof EnInquiryRoute
  '/en/products': typeof EnProductsRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/brands': typeof BrandsIndexRoute
  '/en': typeof EnIndexRoute
  '/en/brands/$brand': typeof EnBrandsBrandRoute
  '/en/products/$slug': typeof EnProductsSlugRoute
  '/en/brands': typeof EnBrandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRouteWithChildren
  '/inquiry': typeof InquiryRoute
  '/products': typeof ProductsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/en/about': typeof EnAboutRoute
  '/en/applications': typeof EnApplicationsRoute
  '/en/contact': typeof EnContactRoute
  '/en/inquiry': typeof EnInquiryRoute
  '/en/products': typeof EnProductsRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/brands/': typeof BrandsIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/brands/$brand': typeof EnBrandsBrandRoute
  '/en/products/$slug': typeof EnProductsSlugRoute
  '/en/brands/': typeof EnBrandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/auth'
    | '/contact'
    | '/en'
    | '/inquiry'
    | '/products'
    | '/admin'
    | '/brands/$brand'
    | '/en/about'
    | '/en/applications'
    | '/en/contact'
    | '/en/inquiry'
    | '/en/products'
    | '/products/$slug'
    | '/brands/'
    | '/en/'
    | '/en/brands/$brand'
    | '/en/products/$slug'
    | '/en/brands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/auth'
    | '/contact'
    | '/inquiry'
    | '/products'
    | '/admin'
    | '/brands/$brand'
    | '/en/about'
    | '/en/applications'
    | '/en/contact'
    | '/en/inquiry'
    | '/en/products'
    | '/products/$slug'
    | '/brands'
    | '/en'
    | '/en/brands/$brand'
    | '/en/products/$slug'
    | '/en/brands'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/applications'
    | '/auth'
    | '/contact'
    | '/en'
    | '/inquiry'
    | '/products'
    | '/_authenticated/admin'
    | '/brands/$brand'
    | '/en/about'
    | '/en/applications'
    | '/en/contact'
    | '/en/inquiry'
    | '/en/products'
    | '/products/$slug'
    | '/brands/'
    | '/en/'
    | '/en/brands/$brand'
    | '/en/products/$slug'
    | '/en/brands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EnRoute: typeof EnRouteWithChildren
  InquiryRoute: typeof InquiryRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  BrandsBrandRoute: typeof BrandsBrandRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/en/products': {
      id: '/en/products'
      path: '/products'
      fullPath: '/en/products'
      preLoaderRoute: typeof EnProductsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/inquiry': {
      id: '/en/inquiry'
      path: '/inquiry'
      fullPath: '/en/inquiry'
      preLoaderRoute: typeof EnInquiryRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/applications': {
      id: '/en/applications'
      path: '/applications'
      fullPath: '/en/applications'
      preLoaderRoute: typeof EnApplicationsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/brands/$brand': {
      id: '/brands/$brand'
      path: '/brands/$brand'
      fullPath: '/brands/$brand'
      preLoaderRoute: typeof BrandsBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/brands/': {
      id: '/en/brands/'
      path: '/brands'
      fullPath: '/en/brands/'
      preLoaderRoute: typeof EnBrandsIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/products/$slug': {
      id: '/en/products/$slug'
      path: '/$slug'
      fullPath: '/en/products/$slug'
      preLoaderRoute: typeof EnProductsSlugRouteImport
      parentRoute: typeof EnProductsRoute
    }
    '/en/brands/$brand': {
      id: '/en/brands/$brand'
      path: '/brands/$brand'
      fullPath: '/en/brands/$brand'
      preLoaderRoute: typeof EnBrandsBrandRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnProductsRouteChildren {
  EnProductsSlugRoute: typeof EnProductsSlugRoute
}

const EnProductsRouteChildren: EnProductsRouteChildren = {
  EnProductsSlugRoute: EnProductsSlugRoute,
}

const EnProductsRouteWithChildren = EnProductsRoute._addFileChildren(
  EnProductsRouteChildren,
)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnApplicationsRoute: typeof EnApplicationsRoute
  EnContactRoute: typeof EnContactRoute
  EnInquiryRoute: typeof EnInquiryRoute
  EnProductsRoute: typeof EnProductsRouteWithChildren
  EnIndexRoute: typeof EnIndexRoute
  EnBrandsBrandRoute: typeof EnBrandsBrandRoute
  EnBrandsIndexRoute: typeof EnBrandsIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnApplicationsRoute: EnApplicationsRoute,
  EnContactRoute: EnContactRoute,
  EnInquiryRoute: EnInquiryRoute,
  EnProductsRoute: EnProductsRouteWithChildren,
  EnIndexRoute: EnIndexRoute,
  EnBrandsBrandRoute: EnBrandsBrandRoute,
  EnBrandsIndexRoute: EnBrandsIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EnRoute: EnRouteWithChildren,
  InquiryRoute: InquiryRoute,
  ProductsRoute: ProductsRouteWithChildren,
  BrandsBrandRoute: BrandsBrandRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
